title: C'est ça | सेसा
subtitle: /sesa/
author: Atul Singh Arora (editor)
email: atul.singh.arora@ulb.ac.be
description: > # this means to ignore newlines until "twitter_username:"
  C'est ça (pronounced /sesɑ/) is intended to be a peer-reviewed journal of popular science articles written in at least two languages.

postEndMaterial: <br/><br/><center> * *  * </center><br/><br/>Bibliography — ग्रन्थसूची


# social links
#twitter_username: jekyllrb
github_username:  C-est-ca
#rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-scholar

scholar:
  style: american-physics-society
    #ieee-with-url
  #american-physics-society
  # bibliography_template: <abbr>[{{key}}]</abbr>{{reference}}
  source: ./_bibliography


encoding: UTF-8